source $HOME/.vim/vimrc_plugin_definitions
source $HOME/.vim/vimrc_settings
source $HOME/.vim/vimrc_mappings
source $HOME/.vim/vimrc_autocmds

if &loadplugins
  source $HOME/.vim/vimrc_plugin_settings
endif

lua require'hop'.setup()
