#! /bin/bash
# This if for the mac hipchat client
# Assumes you have python installed
# To setup, download this file to any folder.
# change the permissions to it is executable using terminal
# `chmod u+x ./hip.sh` or whatever you named the file
# Now you can run `./hip.sh`

echo 'Hipchat hooray...ho... - Press CTRL+C to stop'
while :
do
osascript <<EOF
tell application "Hipchat" to activate

do shell script "
/usr/bin/python <<END

import sys
import time
from Quartz.CoreGraphics import *

def mouseEvent(type, posx, posy):
  theEvent = CGEventCreateMouseEvent(None, type, (posx,posy), kCGMouseButtonLeft)
  CGEventPost(kCGHIDEventTap, theEvent)

def mousemove(posx,posy):
  mouseEvent(kCGEventMouseMoved, posx,posy);

def mouseclick(posx,posy):
  mouseEvent(kCGEventLeftMouseDown, posx,posy);
  mouseEvent(kCGEventLeftMouseUp, posx,posy);

ourEvent = CGEventCreate(None);
currentpos=CGEventGetLocation(ourEvent);
mousemove(int(currentpos.x),int(currentpos.y));
END"
EOF

sleep 100
echo 'Hipchat hooray...ho...'
done
