if [ -f ~/dotfiles/zsh/zsh_aliases ] ; then
  . ~/dotfiles/zsh/zsh_aliases
fi

if [ -f ~/dotfiles/zsh/zsh_path ] ; then
  . ~/dotfiles/zsh/zsh_path
fi

if [ -f ~/dotfiles/zsh/zsh_settings ] ; then
  . ~/dotfiles/zsh/zsh_settings
fi

if [ -f ~/dotfiles/zsh/zsh_functions ] ; then
  . ~/dotfiles/zsh/zsh_functions
fi

if [ -f ~/dotfiles/zsh/zsh_local ] ; then
  . ~/dotfiles/zsh/zsh_local
fi


export NVM_DIR="/Users/avi/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
