if [ -f ~/dotfiles/zsh/zsh_settings ] ; then
  . ~/dotfiles/zsh/zsh_settings
fi

if [ -f ~/dotfiles/zsh/zsh_functions ] ; then
  . ~/dotfiles/zsh/zsh_functions
fi

if [ -f ~/dotfiles/zsh/zsh_local ] ; then
  . ~/dotfiles/zsh/zsh_local
fi

if [ -f ~/dotfiles/zsh/zsh_aliases ] ; then
  . ~/dotfiles/zsh/zsh_aliases
fi

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# if [ -f "$HOME/.asdf/asdf.sh" ]; then
#   source "$HOME/.asdf/asdf.sh"
# fi
#
if [ -f ~/dotfiles/zsh/zsh_path ] ; then
  . ~/dotfiles/zsh/zsh_path
fi
