if [ -f ~/dotfiles/zsh/zsh_aliases ] ; then
  . ~/dotfiles/zsh/zsh_aliases
fi

if [ -f ~/dotfiles/zsh/zsh_path ] ; then
  . ~/dotfiles/zsh/zsh_path
fi

if [ -f ~/dotfiles/zsh/zsh_settings ] ; then
  . ~/dotfiles/zsh/zsh_settings
fi

if [ -f ~/dotfiles/zsh/zsh_functions ] ; then
  . ~/dotfiles/zsh/zsh_functions
fi

if [ -f $(brew --prefix nvm)/nvm.sh ] ; then
  source $(brew --prefix nvm)/nvm.sh
fi
